services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-3}
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "8883:8883"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.rule=Host(`${FQDN_TRAEFIK:-traefik.test}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.service=api@internal"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    depends_on:
      - thingsboard-ce

  postgres:
    restart: always
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    restart: always
    image: bitnamilegacy/kafka:${KAFKA_VERSION}
    ports:
      - 9092:9092 #to localhost:9092 from host machine
      - 9093 #for Kraft
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker" #KRaft
      KAFKA_CFG_NODE_ID: "0" #KRaft
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #KRaft
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093" #KRaft
      KAFKA_CFG_LOG_RETENTION_MS: "300000"
      KAFKA_CFG_SEGMENT_BYTES: "26214400"
    volumes:
      - kafka-data:/bitnami

  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:${THINGSBOARD_VERSION}"
    #    ports:
    #      - "7070:7070"
    #      - "5683-5688:5683-5688/udp"
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thingsboard.rule=Host(`${FQDN_THINGSBOARD:-thingsboard.test}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thingsboard.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-thingsboard.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-thingsboard.loadbalancer.server.port=8080"
      # MQTT TCP Router
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtt.service=${COMPOSE_PROJECT_NAME}-mqtt-service"
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-mqtt-service.loadbalancer.server.port=1883"
      # MQTTS TCP Router (opcional, para MQTT sobre TLS)
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtts.rule=HostSNI(`${FQDN_MQTT:-mqtt.thingsboard.test}`)"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtts.entrypoints=mqtts"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtts.tls=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mqtts.service=${COMPOSE_PROJECT_NAME}-mqtts-service"
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-mqtts-service.loadbalancer.server.port=8883"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: tb-ce-node
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka

  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailpit.rule=Host(`${FQDN_MAILPIT:-mailpit.test}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailpit.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailpit.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-mailpit.loadbalancer.server.port=8025"

volumes:
  postgres-data:
    name: tb-postgres-data
    driver: local
  kafka-data:
    name: tb-ce-kafka-data
    driver: local
